# Generated by Django 3.2.5 on 2021-09-05 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0002_alter_station_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_type', models.CharField(choices=[('tmp', 'Temperature'), ('hum', 'Relative humidity'), ('atm', 'Atmospheric pressure'), ('ws', 'Wind speed'), ('wd', 'Wind direction'), ('pre', 'Precipitation')], max_length=8)),
                ('condition_sign', models.CharField(choices=[('lt', 'less than'), ('lte', 'less than or equal to'), ('eq', 'equal to'), ('gte', 'greater than or equal to'), ('gt', 'greater than')], max_length=32)),
                ('condition_value', models.FloatField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
