# Generated by Django 3.2.5 on 2021-09-07 03:08

from django.db import migrations, models
import stations.models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_station_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=stations.models.OverwriteStorage(), upload_to=stations.models.update_filename),
        ),
    ]
