# Generated by Django 3.2.5 on 2021-09-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_station_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='data',
            field=models.JSONField(unique=True),
        ),
    ]
