# Generated by Django 3.2.5 on 2021-09-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_alter_measure_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='data',
            field=models.JSONField(),
        ),
    ]
